-- 001_initial_schema.sql
-- Stage 1: star schema for Vardhman Traders (schema only, no data).

CREATE TABLE dim_date (
    date_key          integer PRIMARY KEY,           -- YYYYMMDD, e.g. 20260921
    full_date         date    NOT NULL UNIQUE,
    day               smallint NOT NULL CHECK (day BETWEEN 1 AND 31),
    month             smallint NOT NULL CHECK (month BETWEEN 1 AND 12),
    year              smallint NOT NULL,
    day_of_week       varchar(9) NOT NULL,           -- e.g. 'Monday'
    is_monday_holiday boolean NOT NULL DEFAULT false
);

CREATE TABLE dim_order_channel (
    channel_key  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_name varchar(50) NOT NULL UNIQUE          -- Call, Online, Walk-in, Company
);

CREATE TABLE dim_submission_type (
    submission_type_key integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_name           varchar(50) NOT NULL UNIQUE
);

CREATE TABLE dim_delivery_status (
    status_key  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_name varchar(50) NOT NULL UNIQUE
);

CREATE TABLE dim_payment_status (
    payment_status_key integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_name        varchar(50) NOT NULL UNIQUE
);

CREATE TABLE dim_person (
    person_key   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name    varchar(150) NOT NULL,
    phone_number varchar(30),
    person_role  varchar(30) NOT NULL                 -- 'ready_by', 'colour_making', 'delivery'
);

CREATE TABLE dim_user (
    user_key      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      varchar(100) NOT NULL UNIQUE,
    password_hash text         NOT NULL,
    role          varchar(30)  NOT NULL,
    display_name  varchar(150) NOT NULL
);

CREATE TABLE fact_orders (
    order_key                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sl_no                      integer NOT NULL,
    dc_inv_no                  varchar(50),
    order_received_date_key    integer NOT NULL REFERENCES dim_date (date_key),
    order_via_key              integer REFERENCES dim_order_channel (channel_key),
    submission_type_key        integer REFERENCES dim_submission_type (submission_type_key),
    delivery_status_key        integer REFERENCES dim_delivery_status (status_key),
    ready_by_person_key        integer REFERENCES dim_person (person_key),
    colour_making_person_key   integer REFERENCES dim_person (person_key),
    delivered_by_person_key    integer REFERENCES dim_person (person_key),
    payment_status_key         integer REFERENCES dim_payment_status (payment_status_key),
    created_by_user_key        integer REFERENCES dim_user (user_key),
    last_updated_by_user_key   integer REFERENCES dim_user (user_key),
    shipping_location          text,
    detailed_remarks           text,
    timestamp_created          timestamptz NOT NULL DEFAULT now(),
    material_delivery_datetime timestamptz,
    date_of_receiving_key      integer REFERENCES dim_date (date_key),   -- nullable
    last_updated_at            timestamptz,
    amount_received            numeric(10,2),
    cartage                    numeric(10,2),
    is_cancelled               boolean NOT NULL DEFAULT false,
    CONSTRAINT uq_fact_orders_sl_no UNIQUE (sl_no)    -- also creates the unique index on sl_no
);

CREATE INDEX idx_fact_orders_order_received_date_key ON fact_orders (order_received_date_key);
CREATE INDEX idx_fact_orders_delivery_status_key     ON fact_orders (delivery_status_key);
CREATE INDEX idx_fact_orders_dc_inv_no               ON fact_orders (dc_inv_no);
