-- 009: admin portal - bulk upload batches (so an import can be traced and undone) and saved order filters.

CREATE TABLE import_batch (
    batch_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity varchar(20) NOT NULL CHECK (entity IN ('orders', 'users')),
    filename varchar(255),
    row_count integer NOT NULL,
    created_by_user_key integer REFERENCES dim_user (user_key),
    created_at timestamptz NOT NULL DEFAULT now(),
    undone_at timestamptz
);

ALTER TABLE fact_orders ADD COLUMN import_batch_id integer REFERENCES import_batch (batch_id);
ALTER TABLE dim_user ADD COLUMN import_batch_id integer REFERENCES import_batch (batch_id);

CREATE INDEX idx_fact_orders_import_batch ON fact_orders (import_batch_id) WHERE import_batch_id IS NOT NULL;

CREATE TABLE saved_filter (
    filter_key integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_key integer NOT NULL REFERENCES dim_user (user_key) ON DELETE CASCADE,
    name varchar(80) NOT NULL,
    shared boolean NOT NULL DEFAULT FALSE,
    definition jsonb NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_saved_filter_owner_name UNIQUE (owner_user_key, name)
);
