-- 011: page access, access requests, order timeline; saved filters are retired.
--
-- page_access        which roles open which page by default (admin always opens everything, in code)
-- user_page_access   per-person exceptions: allowed = true grants a page, false blocks it, whatever the role says
-- access_request     a person asking an admin for a page they cannot open
-- order_event        one row per change to an order: when, who, and what changed (the order timeline)

CREATE TABLE page_access (
    page_key varchar(40) NOT NULL,
    role     varchar(30) NOT NULL,
    PRIMARY KEY (page_key, role)
);

-- Starting point = how things worked before this migration: each operating role opens its own O2D screen.
INSERT INTO page_access (page_key, role) VALUES
    ('o2d_shop', 'shop'),
    ('o2d_godown', 'godown'),
    ('o2d_shop_dispatch', 'shop_dispatch'),
    ('o2d_godown_dispatch', 'godown_dispatch'),
    ('o2d_receiving', 'receiving');

CREATE TABLE user_page_access (
    user_key            integer NOT NULL REFERENCES dim_user (user_key) ON DELETE CASCADE,
    page_key            varchar(40) NOT NULL,
    allowed             boolean NOT NULL,
    set_by_user_key     integer REFERENCES dim_user (user_key) ON DELETE SET NULL,
    set_at              timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (user_key, page_key)
);

CREATE TABLE access_request (
    request_key         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_key            integer NOT NULL REFERENCES dim_user (user_key) ON DELETE CASCADE,
    page_key            varchar(40) NOT NULL,
    reason              text NOT NULL,
    status              varchar(10) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
    created_at          timestamptz NOT NULL DEFAULT now(),
    decided_by_user_key integer REFERENCES dim_user (user_key) ON DELETE SET NULL,
    decided_at          timestamptz,
    decision_note       text
);
CREATE INDEX idx_access_request_status ON access_request (status, created_at DESC);
-- one open request per person per page
CREATE UNIQUE INDEX uq_access_request_pending ON access_request (user_key, page_key) WHERE status = 'pending';

CREATE TABLE order_event (
    event_key   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_key   integer NOT NULL REFERENCES fact_orders (order_key) ON DELETE CASCADE,
    at          timestamptz NOT NULL DEFAULT now(),
    event_type  varchar(20) NOT NULL,
    title       varchar(120) NOT NULL,
    by_user_key integer REFERENCES dim_user (user_key) ON DELETE SET NULL,
    by_name     varchar(150),
    by_role     varchar(30),
    changes     jsonb
);
CREATE INDEX idx_order_event_order ON order_event (order_key, at);

DROP TABLE saved_filter;
