-- Admin reminders: a nudge about one order, shown to the people who handle its current stage until they acknowledge it.
CREATE TABLE order_reminder (
    reminder_key        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_key           integer NOT NULL REFERENCES fact_orders (order_key) ON DELETE CASCADE,
    stage               varchar(30) NOT NULL,          -- the stage the order was in when the reminder was sent
    message             varchar(300),
    sent_by_user_key    integer REFERENCES dim_user (user_key) ON DELETE SET NULL,
    sent_by_name        varchar(150),
    sent_at             timestamptz NOT NULL DEFAULT now(),
    acked_by_name       varchar(150),
    acked_at            timestamptz
);
CREATE INDEX idx_order_reminder_open ON order_reminder (stage) WHERE acked_at IS NULL;
