-- A missing bill number that was looked into and found not to need punching (e.g. voided in BUSY).
-- Gaps themselves are never stored: they are worked out from the orders. Only this explanation is kept.
-- series_key: the order date (YYYY-MM-DD) for the daily Challan series, the financial year (e.g. 2026-27) for Invoice.
CREATE TABLE doc_gap_void (
    void_key        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_type        varchar(10) NOT NULL CHECK (doc_type IN ('Challan', 'Invoice')),
    series_key      varchar(10) NOT NULL,
    doc_no          integer NOT NULL,
    reason          varchar(300) NOT NULL,
    by_user_key     integer REFERENCES dim_user (user_key) ON DELETE SET NULL,
    by_name         varchar(150),
    at              timestamptz NOT NULL DEFAULT now(),
    UNIQUE (doc_type, series_key, doc_no)
);
