-- 014: Delivered-by detail, per-role delivery lists, photo attachments.
--
-- delivered_by_detail: free text filled in when "Delivered by" is Porter / By Company / Transport
--   (which values trigger it is the admin setting app_config 'delivered_by_custom_terms').
-- dim_person.dispatch_scope: which dispatch screen offers a "Delivered by" person: both | shop | godown.
-- order_attachments: photos taken at dispatch / receiving, stored in Cloudflare R2 (only the key lives here).

ALTER TABLE fact_orders ADD COLUMN delivered_by_detail varchar(200);

ALTER TABLE dim_person ADD COLUMN dispatch_scope varchar(10) NOT NULL DEFAULT 'both'
    CHECK (dispatch_scope IN ('both', 'shop', 'godown'));

INSERT INTO role_field_permissions (role, field_name) VALUES
    ('shop_dispatch', 'delivered_by_detail'), ('godown_dispatch', 'delivered_by_detail')
ON CONFLICT DO NOTHING;

CREATE TABLE order_attachments (
    attachment_key  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_key       integer NOT NULL REFERENCES fact_orders (order_key) ON DELETE CASCADE,
    kind            varchar(20) NOT NULL CHECK (kind IN ('dispatch', 'receiving')),
    object_key      varchar(300) NOT NULL UNIQUE,
    content_type    varchar(100) NOT NULL,
    size_bytes      integer NOT NULL,
    uploaded_by_key integer REFERENCES dim_user (user_key) ON DELETE SET NULL,
    uploaded_by     varchar(150),
    uploaded_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_order_attachments_order ON order_attachments (order_key);

-- Appending a column at the end is the only change CREATE OR REPLACE VIEW allows.
CREATE OR REPLACE VIEW v_orders AS
SELECT
    o.order_key, o.sl_no, o.dc_inv_no,
    d.full_date                   AS order_date,
    c.channel_name                AS channel,
    st.type_name                  AS submission_type,
    ds.status_name                AS delivery_status,
    ps.status_name                AS payment_status,
    rp.full_name                  AS ready_by,
    cp.full_name                  AS colour_making_by,
    dp.full_name                  AS delivered_by,
    dp.phone_number               AS delivered_by_phone,
    cu.display_name               AS created_by,
    lu.display_name               AS last_updated_by,
    o.shipping_location, o.detailed_remarks,
    o.timestamp_created, o.material_delivery_datetime,
    rd.full_date                  AS date_of_receiving,
    o.last_updated_at, o.amount_received, o.cartage, o.is_cancelled,
    CASE
        WHEN o.is_cancelled OR lower(btrim(st.type_name)) = 'cancelled' THEN 'Cancelled'
        WHEN o.delivery_status_key IS NULL                              THEN 'Awaiting godown'
        WHEN o.material_delivery_datetime IS NULL                       THEN 'Awaiting dispatch'
        WHEN o.date_of_receiving_key IS NULL OR o.payment_status_key IS NULL THEN 'Awaiting receiving'
        ELSE 'Closed'
    END AS stage,
    CASE
        WHEN NOT (o.is_cancelled OR lower(btrim(st.type_name)) = 'cancelled')
             AND o.material_delivery_datetime >= o.timestamp_created
        THEN EXTRACT(EPOCH FROM (o.material_delivery_datetime - o.timestamp_created)) / 3600.0
    END AS hours_to_deliver,
    o.archived_at,
    o.delivered_by_detail
FROM fact_orders o
JOIN dim_date d ON d.date_key = o.order_received_date_key
LEFT JOIN dim_date rd            ON rd.date_key = o.date_of_receiving_key
LEFT JOIN dim_order_channel c    ON c.channel_key = o.order_via_key
LEFT JOIN dim_submission_type st ON st.submission_type_key = o.submission_type_key
LEFT JOIN dim_delivery_status ds ON ds.status_key = o.delivery_status_key
LEFT JOIN dim_payment_status ps  ON ps.payment_status_key = o.payment_status_key
LEFT JOIN dim_person rp          ON rp.person_key = o.ready_by_person_key
LEFT JOIN dim_person cp          ON cp.person_key = o.colour_making_person_key
LEFT JOIN dim_person dp          ON dp.person_key = o.delivered_by_person_key
LEFT JOIN dim_user cu            ON cu.user_key = o.created_by_user_key
LEFT JOIN dim_user lu            ON lu.user_key = o.last_updated_by_user_key
WHERE o.archived_at IS NULL;

CREATE OR REPLACE VIEW v_orders_archive AS
SELECT
    o.order_key, o.sl_no, o.dc_inv_no,
    d.full_date                   AS order_date,
    c.channel_name                AS channel,
    st.type_name                  AS submission_type,
    ds.status_name                AS delivery_status,
    ps.status_name                AS payment_status,
    rp.full_name                  AS ready_by,
    cp.full_name                  AS colour_making_by,
    dp.full_name                  AS delivered_by,
    dp.phone_number               AS delivered_by_phone,
    cu.display_name               AS created_by,
    lu.display_name               AS last_updated_by,
    o.shipping_location, o.detailed_remarks,
    o.timestamp_created, o.material_delivery_datetime,
    rd.full_date                  AS date_of_receiving,
    o.last_updated_at, o.amount_received, o.cartage, o.is_cancelled,
    CASE
        WHEN o.is_cancelled OR lower(btrim(st.type_name)) = 'cancelled' THEN 'Cancelled'
        WHEN o.delivery_status_key IS NULL                              THEN 'Awaiting godown'
        WHEN o.material_delivery_datetime IS NULL                       THEN 'Awaiting dispatch'
        WHEN o.date_of_receiving_key IS NULL OR o.payment_status_key IS NULL THEN 'Awaiting receiving'
        ELSE 'Closed'
    END AS stage,
    CASE
        WHEN NOT (o.is_cancelled OR lower(btrim(st.type_name)) = 'cancelled')
             AND o.material_delivery_datetime >= o.timestamp_created
        THEN EXTRACT(EPOCH FROM (o.material_delivery_datetime - o.timestamp_created)) / 3600.0
    END AS hours_to_deliver,
    o.archived_at,
    o.delivered_by_detail
FROM fact_orders o
JOIN dim_date d ON d.date_key = o.order_received_date_key
LEFT JOIN dim_date rd            ON rd.date_key = o.date_of_receiving_key
LEFT JOIN dim_order_channel c    ON c.channel_key = o.order_via_key
LEFT JOIN dim_submission_type st ON st.submission_type_key = o.submission_type_key
LEFT JOIN dim_delivery_status ds ON ds.status_key = o.delivery_status_key
LEFT JOIN dim_payment_status ps  ON ps.payment_status_key = o.payment_status_key
LEFT JOIN dim_person rp          ON rp.person_key = o.ready_by_person_key
LEFT JOIN dim_person cp          ON cp.person_key = o.colour_making_person_key
LEFT JOIN dim_person dp          ON dp.person_key = o.delivered_by_person_key
LEFT JOIN dim_user cu            ON cu.user_key = o.created_by_user_key
LEFT JOIN dim_user lu            ON lu.user_key = o.last_updated_by_user_key;
