-- 016: the Payments, Delegation and Purchase modules, on the same star schema as O2D.
--
-- Reused, not recreated:   dim_user (staff, cashiers, creators, approvers), dim_date (every date),
--                          app_config (module settings), admin_audit_log, page_access / user_page_access.
-- New shared masters:      dim_company, dim_payment_mode, dim_txn_type, dim_party (payment parties AND purchase vendors),
--                          dim_purchase_site, file_attachment (photos for any module, stored in R2).
-- New facts:               fact_payment_txn, fact_task, fact_weekly_plan, fact_extra_work, fact_purchase_entry.

-- ------------------------------------------------------------------ shared masters
CREATE TABLE dim_company (
    company_key      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name     varchar(100) NOT NULL,
    is_sales_company boolean NOT NULL DEFAULT false,   -- its cash sales feed the "Cash Sales" card
    sort_order       integer NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX uq_dim_company_name ON dim_company (lower(btrim(company_name)));

CREATE TABLE dim_payment_mode (
    mode_key       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mode_name      varchar(50) NOT NULL,
    is_cash        boolean NOT NULL DEFAULT false,    -- counts toward cash in hand
    needs_approval boolean NOT NULL DEFAULT false,    -- a cashier's entry in this mode waits for the account team
    sort_order     integer NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX uq_dim_payment_mode_name ON dim_payment_mode (lower(btrim(mode_name)));

CREATE TABLE dim_txn_type (
    txn_type_key integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_name    varchar(50) NOT NULL,
    direction    varchar(3) NOT NULL CHECK (direction IN ('in', 'out')),
    affects_bank boolean NOT NULL DEFAULT true,       -- false: moves between cash and bank, not counted in the bank balance
    sales_effect smallint NOT NULL DEFAULT 0 CHECK (sales_effect IN (-1, 0, 1)),   -- +1 adds to cash sales, -1 takes away
    entry_allowed boolean NOT NULL DEFAULT true,       -- offered in the New Entry form (still shown when editing/filtering)
    counts_as_received boolean NOT NULL DEFAULT false, -- adds to the "Total Received" card (and is what that card lists)
    counts_as_paid     boolean NOT NULL DEFAULT false, -- adds to the "Total Paid" card
    sort_order   integer NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX uq_dim_txn_type_name ON dim_txn_type (lower(btrim(type_name)));

-- One list of parties for everything that has a "name of the other side": payment parties (per company and, optionally,
-- per transaction type) and purchase vendors. Blank company / type = offered everywhere.
CREATE TABLE dim_party (
    party_key    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    party_name   varchar(150) NOT NULL,
    party_kind   varchar(10) NOT NULL DEFAULT 'payment' CHECK (party_kind IN ('payment', 'vendor')),
    company_key  integer REFERENCES dim_company (company_key),
    txn_type_key integer REFERENCES dim_txn_type (txn_type_key)
);
CREATE UNIQUE INDEX uq_dim_party ON dim_party (lower(btrim(party_name)), party_kind, COALESCE(company_key, 0), COALESCE(txn_type_key, 0));

CREATE TABLE dim_purchase_site (
    site_key  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_slug varchar(20) NOT NULL UNIQUE,
    site_name varchar(50) NOT NULL
);
INSERT INTO dim_purchase_site (site_slug, site_name) VALUES ('godown', 'Godown'), ('shop', 'Shop');

-- Photos for any module. The bytes live in R2; this keeps the key and who/when. module + record_key say what it belongs to.
CREATE TABLE file_attachment (
    attachment_key  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module          varchar(20) NOT NULL,
    record_key      bigint NOT NULL,
    kind            varchar(30) NOT NULL DEFAULT 'photo',
    object_key      varchar(300) NOT NULL UNIQUE,
    content_type    varchar(100) NOT NULL,
    size_bytes      integer NOT NULL,
    uploaded_by_key integer REFERENCES dim_user (user_key) ON DELETE SET NULL,
    uploaded_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_file_attachment_record ON file_attachment (module, record_key);

-- ------------------------------------------------------------------ payments
CREATE TABLE fact_payment_txn (
    txn_key             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    txn_no              text GENERATED ALWAYS AS ('TXN-' || lpad(txn_key::text, 4, '0')) STORED,
    txn_date_key        integer NOT NULL REFERENCES dim_date (date_key),
    txn_type_key        integer NOT NULL REFERENCES dim_txn_type (txn_type_key),
    company_key         integer NOT NULL REFERENCES dim_company (company_key),
    party_key           integer REFERENCES dim_party (party_key),
    mode_key            integer NOT NULL REFERENCES dim_payment_mode (mode_key),
    amount              numeric(14, 2) NOT NULL CHECK (amount > 0),
    account_name        varchar(150),
    invoice_no          varchar(80),
    remarks             text,
    status              varchar(10) NOT NULL DEFAULT 'Pending' CHECK (status IN ('Pending', 'Approved', 'Rejected')),
    is_backdated        boolean NOT NULL DEFAULT false,
    created_by_user_key integer REFERENCES dim_user (user_key),
    created_at          timestamptz NOT NULL DEFAULT now(),
    approved_by_user_key integer REFERENCES dim_user (user_key),
    approved_at         timestamptz,
    updated_at          timestamptz
);
CREATE INDEX idx_payment_txn_date ON fact_payment_txn (txn_date_key);
CREATE INDEX idx_payment_txn_status ON fact_payment_txn (status);

-- ------------------------------------------------------------------ delegation
CREATE TABLE fact_task (
    task_key            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_no             text GENERATED ALWAYS AS ('T-' || lpad(task_key::text, 5, '0')) STORED,
    staff_user_key      integer NOT NULL REFERENCES dim_user (user_key),
    assigned_by_user_key integer REFERENCES dim_user (user_key),
    description         text NOT NULL,
    assigned_date_key   integer NOT NULL REFERENCES dim_date (date_key),
    due_date_key        integer NOT NULL REFERENCES dim_date (date_key),
    status              varchar(20) NOT NULL DEFAULT 'Pending'
                        CHECK (status IN ('Pending', 'Completed By Staff', 'Approved', 'Rejected')),
    completed_date_key  integer REFERENCES dim_date (date_key),
    extra_work_notes    text,
    remark              text,
    score               integer,                     -- null until the staff member submits
    revision_count      smallint NOT NULL DEFAULT 0, -- sent back by the manager after submitting
    extension_count     smallint NOT NULL DEFAULT 0, -- deadline moved after being missed
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz
);
CREATE INDEX idx_task_staff ON fact_task (staff_user_key);
CREATE INDEX idx_task_due ON fact_task (due_date_key);

CREATE TABLE fact_weekly_plan (
    plan_key          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_user_key    integer NOT NULL REFERENCES dim_user (user_key),
    week_start_key    integer NOT NULL REFERENCES dim_date (date_key),
    green_pct         numeric(5, 2) NOT NULL,
    yellow_pct        numeric(5, 2) NOT NULL,
    red_pct           numeric(5, 2) NOT NULL,
    saved_at          timestamptz NOT NULL DEFAULT now(),
    UNIQUE (staff_user_key, week_start_key),
    CHECK (green_pct + yellow_pct + red_pct BETWEEN 99.5 AND 100.5)
);

CREATE TABLE fact_extra_work (
    extra_key      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_key       integer NOT NULL REFERENCES dim_user (user_key),
    work_date_key  integer NOT NULL REFERENCES dim_date (date_key),
    description    text NOT NULL,
    created_at     timestamptz NOT NULL DEFAULT now()
);

-- ------------------------------------------------------------------ purchase
CREATE TABLE fact_purchase_entry (
    purchase_key           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_key               integer NOT NULL REFERENCES dim_purchase_site (site_key),
    vendor_party_key       integer NOT NULL REFERENCES dim_party (party_key),
    material_received_date_key integer REFERENCES dim_date (date_key),
    invoice_date_key       integer REFERENCES dim_date (date_key),
    invoice_no             varchar(80),
    invoice_amount         numeric(14, 2),
    remarks                text,
    created_by_user_key    integer REFERENCES dim_user (user_key),
    created_at             timestamptz NOT NULL DEFAULT now(),
    updated_by_user_key    integer REFERENCES dim_user (user_key),
    updated_at             timestamptz
);
CREATE INDEX idx_purchase_site ON fact_purchase_entry (site_key);
CREATE INDEX idx_purchase_vendor ON fact_purchase_entry (vendor_party_key);

-- ------------------------------------------------------------------ starting values (all editable under Setup)
INSERT INTO dim_payment_mode (mode_name, is_cash, needs_approval, sort_order) VALUES
    ('Cash', true, false, 1), ('Bank', false, false, 2), ('UPI', false, false, 3), ('Cheque', false, false, 4),
    ('Card', false, false, 5), ('Receiving Signed Copy', false, false, 6), ('DEVU', false, false, 7),
    ('PENDING', false, true, 8), ('DIARY', false, false, 9);

-- Total Received / Total Paid follow what the cards say: "Payment Received only" and "Payment Paid + Expense". (The old script's
-- totals also added Sales, Cash Deposit, Cash Withdrawn and Sale Return, so the card did not match the entries it listed.)
INSERT INTO dim_txn_type (type_name, direction, affects_bank, sales_effect, entry_allowed, counts_as_received, counts_as_paid, sort_order) VALUES
    ('Payment Received', 'in', true, 0, true, true, false, 1), ('Payment Paid', 'out', true, 0, true, false, true, 2),
    ('Sales', 'in', true, 1, true, false, false, 3), ('Sales Cash', 'in', true, 1, false, false, false, 4),
    ('Expense', 'out', true, 0, true, false, true, 5), ('Cash Deposit', 'in', false, 0, true, false, false, 6),
    ('Cash Withdrawn', 'out', false, 0, true, false, false, 7), ('Sale Return', 'out', true, -1, true, false, false, 8);

INSERT INTO dim_company (company_name, is_sales_company, sort_order) VALUES
    ('IRIS', false, 1), ('VT', true, 2), ('ASIAN', true, 3), ('TEXTURE', false, 4), ('OIKOS', false, 5),
    ('W.H.S.', false, 6), ('WALLPAPER', false, 7), ('Ritesh Personal Account', false, 8), ('Rajni Personal Account', false, 9);

-- Delegation scoring rules (Setup > Module settings). Starting values.
INSERT INTO app_config (key, value) VALUES
    ('deleg_on_time_score', '10'), ('deleg_late_score', '-5'), ('deleg_revise_penalty', '-3'),
    ('deleg_extend_penalty', '-5'), ('deleg_week_start_dow', '6')
ON CONFLICT (key) DO NOTHING;

-- ------------------------------------------------------------------ access: who opens which module page (editable under Setup > Access)
INSERT INTO page_access (page_key, role) VALUES
    ('pay_cashier', 'cashier'), ('pay_account', 'accounts'),
    ('deleg_mine', 'staff'), ('deleg_week', 'staff'), ('deleg_scoreboard', 'staff'),
    ('deleg_mine', 'manager'), ('deleg_week', 'manager'), ('deleg_scoreboard', 'manager'), ('deleg_manage', 'manager'),
    ('po_godown', 'purchase_godown'), ('po_shop', 'purchase_shop')
ON CONFLICT DO NOTHING;
