-- 017: the vendor names the Purchase screen had typed into its page, now in the shared party list
-- (Setup > Dropdown values > Vendors). Same names, nothing added or dropped; merge look-alikes there, e.g. the two
-- 'Woodver Coatings' spellings or 'Teknovace Wood Coatings' (Private Limited / Pvt Ltd).
INSERT INTO dim_party (party_name, party_kind) VALUES
    ('A K PAINTS & HARDWARE STORE', 'vendor'),
    ('Acro Paints Limited', 'vendor'),
    ('AEROSTAR ENTERPRISES', 'vendor'),
    ('Aggarwal Pumps & Electricals', 'vendor'),
    ('Aggarwal Traders', 'vendor'),
    ('Aitalia Coats Pvt.Ltd.', 'vendor'),
    ('Akanksha Enterprises', 'vendor'),
    ('Akki Enterprises', 'vendor'),
    ('Akshat Enterprises', 'vendor'),
    ('Akzo Nobel India Ltd', 'vendor'),
    ('Amar Sons', 'vendor'),
    ('AMBA TRADERS', 'vendor'),
    ('Amit Granites', 'vendor'),
    ('Amit Paints', 'vendor'),
    ('Amyra Bath & Tiles Studio', 'vendor'),
    ('Analco India Company', 'vendor'),
    ('ARC CERAMICS', 'vendor'),
    ('ASHISH AGENCIES', 'vendor'),
    ('Ashok Kumar Khandelwal', 'vendor'),
    ('Asian Paints Limited', 'vendor'),
    ('B L K Enterprises Private Limited', 'vendor'),
    ('Balaji Brushware', 'vendor'),
    ('Bansal Trading & Contractors', 'vendor'),
    ('Bansi Lal & Sons', 'vendor'),
    ('Beena Agency', 'vendor'),
    ('Berger Paints India Ltd.', 'vendor'),
    ('BHARAT MARBLE HOUSE', 'vendor'),
    ('BIHANI MARKETING PVT.LTD.', 'vendor'),
    ('Bosny Spray Paints', 'vendor'),
    ('BSC Paints Private Limited', 'vendor'),
    ('Business Alert Infotech Private Limited', 'vendor'),
    ('CEOITBOX TECH SERVICES LLP', 'vendor'),
    ('Chaudhary Paint & Hardware', 'vendor'),
    ('CHAVI SALES', 'vendor'),
    ('Chhabra Trading Co.', 'vendor'),
    ('City Paints', 'vendor'),
    ('Colormate Wood Solutions LLP', 'vendor'),
    ('Compact Softwares & Services', 'vendor'),
    ('CSS Infotech', 'vendor'),
    ('Deepika Minerals And Chemicals', 'vendor'),
    ('Delhi Cement Distributors', 'vendor'),
    ('Designers Delight Inc.', 'vendor'),
    ('Dev Colour & Coatings Pvt. Ltd.', 'vendor'),
    ('Devender & Partner Sales Corporation', 'vendor'),
    ('Devi Paints & Cement Store', 'vendor'),
    ('Diamond Agencies', 'vendor'),
    ('DIZITAL CARD SOLUTIONS', 'vendor'),
    ('DT Sales', 'vendor'),
    ('Durga Mill Store Private Limited', 'vendor'),
    ('Durga Plaster', 'vendor'),
    ('ECHOBOOOM MANAGEMENT & ENTREPRENEURIAL SOLUTIONS PRIVATE LIM', 'vendor'),
    ('ESDEE Paints Limited', 'vendor'),
    ('EXCITEL BROADBAND PVT. LTD', 'vendor'),
    ('Firetech Engineers Works', 'vendor'),
    ('Floor & Decor', 'vendor'),
    ('G S Sales Corporation', 'vendor'),
    ('GANPATI TRADERS', 'vendor'),
    ('GARG TRADERS', 'vendor'),
    ('Gateway Peripherals Pvt Ltd', 'vendor'),
    ('Gopal Agencies', 'vendor'),
    ('GORA PAINTS INDIA', 'vendor'),
    ('Grasim Industries Limited', 'vendor'),
    ('Gupta Oil', 'vendor'),
    ('Gupta Sales Corporation', 'vendor'),
    ('Guru Ramdas Trading Company', 'vendor'),
    ('Haryana Hardware Store Private Limited', 'vendor'),
    ('Hind Rapid Trading Co.', 'vendor'),
    ('HINDUSTAN HARDWARE & PAINT STORE', 'vendor'),
    ('Home & Indl. International Coatings', 'vendor'),
    ('Hylite Brushware Co', 'vendor'),
    ('IMGUARD INNOVATIONS PRIVATE LIMITED', 'vendor'),
    ('India Marketing', 'vendor'),
    ('Indigo Paints Limited', 'vendor'),
    ('Innovative Merchant', 'vendor'),
    ('J D I Paints Industries', 'vendor'),
    ('J.K.Cement Ltd.', 'vendor'),
    ('Jai Brushware', 'vendor'),
    ('Jai Durga Traders', 'vendor'),
    ('Jai Durge Enterprises', 'vendor'),
    ('Jai Mata Trading Co.', 'vendor'),
    ('Jain Paint & Sanitary Store', 'vendor'),
    ('JAJU MARBLE HOUSE', 'vendor'),
    ('JKC Wood Amore', 'vendor'),
    ('JMD', 'vendor'),
    ('JSW Dulux Limited', 'vendor'),
    ('Jubilant Agri and Consumer Products Ltd', 'vendor'),
    ('JUST SPRAY MARKETING PRIVATE LIMITED', 'vendor'),
    ('JYOTI SALES CORPORATION', 'vendor'),
    ('K.G.Traders', 'vendor'),
    ('Kaara Decor Pvt. Ltd.', 'vendor'),
    ('Kamal Tools', 'vendor'),
    ('Kanchan Radios', 'vendor'),
    ('Kansai Nerolac Paints Limited', 'vendor'),
    ('Kapoor Brothers', 'vendor'),
    ('KC Good Shine Paints Private Limited', 'vendor'),
    ('Khaitan Sales', 'vendor'),
    ('Kirpal Brush Private Limited', 'vendor'),
    ('Knop Trading Co.', 'vendor'),
    ('Krishna Chemicals', 'vendor'),
    ('Krishna Enterprises', 'vendor'),
    ('Krishna Global', 'vendor'),
    ('Krishna Paints & Chemicals', 'vendor'),
    ('Krishna Sales Corporation', 'vendor'),
    ('Krishna Traders', 'vendor'),
    ('KRISHNAJI ENTERPRISES', 'vendor'),
    ('Laxmi Narayan Enterprises', 'vendor'),
    ('Life Care International', 'vendor'),
    ('LMS PAINTS LLP', 'vendor'),
    ('M.K.TRADERS', 'vendor'),
    ('M/S ZYDEX INDUSTRIES PRIVATE LIMITED', 'vendor'),
    ('M/s Shree Floor Prints', 'vendor'),
    ('M/S VIKRAM PAINTS & SANITARY STORE', 'vendor'),
    ('Mahabir Prashad Jain & Co.', 'vendor'),
    ('Mahalaxmi Sales', 'vendor'),
    ('Malhotra Paints', 'vendor'),
    ('Mangla Traders', 'vendor'),
    ('Marigold Paints Pvt Ltd', 'vendor'),
    ('Marmo Solutions Pvt Ltd', 'vendor'),
    ('Meenu Enterprises Prop Raj Kumar Paswan', 'vendor'),
    ('Mehra Paint Mart', 'vendor'),
    ('Mibuild Private Limited', 'vendor'),
    ('Micro Systems World', 'vendor'),
    ('MOHIT PAINT & H/W', 'vendor'),
    ('Monga Traders', 'vendor'),
    ('MOSAI INSTITUTE OF JAPANESE LANGUAGE', 'vendor'),
    ('Mrf Corp Limited', 'vendor'),
    ('N.R Minerals', 'vendor'),
    ('National Gift Bazar', 'vendor'),
    ('Nav Bharat Trading Corporation', 'vendor'),
    ('New Color Co.', 'vendor'),
    ('New Super Sales Industries', 'vendor'),
    ('New Wembley Products LLP', 'vendor'),
    ('NEXT-I SYSTEM', 'vendor'),
    ('Nippon Paint India Private Limitd', 'vendor'),
    ('Novelty Paint House', 'vendor'),
    ('Nuova Sivam And Genver Coatings Pvt Ltd', 'vendor'),
    ('OAKCRAFT', 'vendor'),
    ('Om Sons Paints India', 'vendor'),
    ('Onyx Coatings Private Limited', 'vendor'),
    ('Oriental Airport Systems', 'vendor'),
    ('ORIENTAL COLOUR & COATINGS', 'vendor'),
    ('Oshin Enterprises', 'vendor'),
    ('P.P Sales', 'vendor'),
    ('Pai Cristal India Pvt Ltd', 'vendor'),
    ('PAN INFOTECH', 'vendor'),
    ('PAPPU ELECTRICAL', 'vendor'),
    ('PARAS TRADERS', 'vendor'),
    ('Pawan Paints', 'vendor'),
    ('Pcvimal Private Limited', 'vendor'),
    ('Pidilite Industries Limited', 'vendor'),
    ('PIDILITE PIGMENT INDUSTRIES', 'vendor'),
    ('Premier Agencies', 'vendor'),
    ('Prive International', 'vendor'),
    ('PYARE LAL PAINTS', 'vendor'),
    ('R.K Impex', 'vendor'),
    ('RADHA KRISHNA EXIM', 'vendor'),
    ('Rajput Traders', 'vendor'),
    ('Ram Avtar & Sons', 'vendor'),
    ('Rockland Buildcare Pvt . Ltd.', 'vendor'),
    ('ROHINI CERAMICS PRIVATE LIMITED', 'vendor'),
    ('Roy Paints Pvt Ltd.', 'vendor'),
    ('Rudraksh Enterprises', 'vendor'),
    ('Rushabh Agencies', 'vendor'),
    ('S C Marketing', 'vendor'),
    ('S P Enterprises', 'vendor'),
    ('S.S. TRADERS', 'vendor'),
    ('S.S.ENTERPRISES', 'vendor'),
    ('Sabharwall Trading Co', 'vendor'),
    ('Sai Agency', 'vendor'),
    ('Sai Trading Company', 'vendor'),
    ('Saini Paint & Hardware Store', 'vendor'),
    ('Salcreat Manufacturing Pvt Ltd', 'vendor'),
    ('Sam Enterprises', 'vendor'),
    ('Samartha Shades & Textures Private Limit', 'vendor'),
    ('Sant Ram Nikka Mal', 'vendor'),
    ('Sarna Automotives India', 'vendor'),
    ('Sarvodaya Enterprises', 'vendor'),
    ('Saurashtra Cement Limited', 'vendor'),
    ('Sawan Mal Amir Chand', 'vendor'),
    ('SCOOTSY LOGISTICS PRIVATE LIMITED', 'vendor'),
    ('Sewing Corporation (India)', 'vendor'),
    ('Shalimar Paints Limited', 'vendor'),
    ('SHAWH G.V. PRIVATE LIMITED', 'vendor'),
    ('Shiv Sanitary Store', 'vendor'),
    ('Shivaay Trading Co.', 'vendor'),
    ('Shivam Sales Corporation', 'vendor'),
    ('Shree Krishna Sales Corporation', 'vendor'),
    ('Shri Balaji Granite', 'vendor'),
    ('Shri Balaji Plastic', 'vendor'),
    ('Shri Kishan & Sons', 'vendor'),
    ('Shri Ram Chander Manoj Kumar & Son', 'vendor'),
    ('Shri Shyam Enterprises', 'vendor'),
    ('Shyam Paints H/W & Sanitary Store(P) Ltd', 'vendor'),
    ('SHYAM TRADERS', 'vendor'),
    ('Silicone Concepts International Private', 'vendor'),
    ('Singla Traders', 'vendor'),
    ('Sirca Paints India Limited', 'vendor'),
    ('SK Stone Chemical', 'vendor'),
    ('Sparsh International (India)', 'vendor'),
    ('SPRAYTECH INTERNATIONAL', 'vendor'),
    ('Stenna Wallpapers Pvt Ltd', 'vendor'),
    ('Sukhija Brothers', 'vendor'),
    ('Sunny Traders', 'vendor'),
    ('Super Paints Corporation', 'vendor'),
    ('TEKNOVACE WOOD COATINGS PRIVATE LIMITED', 'vendor'),
    ('Teknovace Wood Coatings Pvt Ltd', 'vendor'),
    ('The Elementto Lifestyles', 'vendor'),
    ('The New India Assurance Co Limited', 'vendor'),
    ('TRIMURTI WALL CARE PRODUCTS (DL)', 'vendor'),
    ('Trimurti Wall Care Products Pvt Ltd', 'vendor'),
    ('Triwax Polychem', 'vendor'),
    ('UDC IMPEX LLP', 'vendor'),
    ('Ultratech Cement Limited', 'vendor'),
    ('Unique Stone Solutions', 'vendor'),
    ('United Marble House', 'vendor'),
    ('Urban Traders', 'vendor'),
    ('UV Colour Pvt Ltd', 'vendor'),
    ('Vaani Impx', 'vendor'),
    ('Vardhman Compusoft', 'vendor'),
    ('Vardhman Computer & Communications', 'vendor'),
    ('VENIMADHAV DESIGNS PRIVATE LIMITED', 'vendor'),
    ('Venimadhav Traders', 'vendor'),
    ('Venus Stationers & Suppliers', 'vendor'),
    ('VIJAY SALES', 'vendor'),
    ('VISTA FURNISHING LIMITED', 'vendor'),
    ('Wall Paradise', 'vendor'),
    ('Wallart Wallpaper Pvt Ltd', 'vendor'),
    ('Welcome Sales Corporation', 'vendor'),
    ('Wembley Sales Corporation', 'vendor'),
    ('Woodco Paints Private Limited', 'vendor'),
    ('Woodver Coatings Private Limited', 'vendor'),
    ('Woodver Coatings Pvt Ltd', 'vendor'),
    ('WTE Enterprises', 'vendor'),
    ('Yadhuvanshi Infratech P Ltd', 'vendor'),
    ('YASHIKA ENTTERPRISES', 'vendor'),
    ('Yogesh Agencies', 'vendor')
ON CONFLICT DO NOTHING;
