-- 023: automatic daily delivery reports. At 7:30 PM IST the app builds one PDF per delivery person (godown dispatch) with every order
-- that person delivered that day. The PDFs are kept here so they can be downloaded later; daily_report_run says a day has been done.

CREATE TABLE daily_delivery_report (
    report_key bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_date date NOT NULL,
    person_name varchar(150) NOT NULL,
    order_count integer NOT NULL,
    pdf bytea NOT NULL,
    generated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_daily_delivery_report UNIQUE (report_date, person_name)
);

CREATE TABLE daily_report_run (
    report_date date PRIMARY KEY,
    ran_at timestamptz NOT NULL DEFAULT now(),
    persons integer NOT NULL
);

-- The WhatsApp summary of the day (one message listing every person): group and wording are set under Setup > WhatsApp.
-- No group is set here, so nothing is sent until an admin fills it in.
INSERT INTO whatsapp_alert (alert_key, label, template)
SELECT
    'delivery_day_summary' AS alert_key,
    'Daily delivery summary (7:30 PM)' AS label,
    concat_ws(chr(10), 'Delivery summary - {date}', '', '{summary}') AS template;
